_home:
    path: /
    defaults: { _controller: CrazysunMainBundle:Default:index }

_home_admin:
    path:     /admin
    defaults: { _controller: CrazysunMainBundle:Default:admin }

_ad:
    path: /admin/teasers
    defaults: { _controller: CrazysunMainBundle:Default:teasers }

_new_ad:
    path: /admin/teasers/new
    defaults: { _controller: CrazysunMainBundle:Default:teasersNew }